format = """
$os$username$hostname$directory$git_branch$git_status$git_state$cmd_duration
$line_break$character
"""

palette = "tokyo_night"

[palettes.tokyo_night]
bg = "#1a1b26"
fg = "#c0caf5"
blue = "#7aa2f7"
purple = "#bb9af7"
cyan = "#7dcfff"
green = "#9ece6a"
orange = "#ff9e64"
yellow = "#e0af68"
red = "#f7768e"
comment = "#565f89"

[os]
disabled = false
format = "[$symbol]($style)"
style = "bold fg:purple"

[username]
show_always = true
style_user = "bold fg:yellow"
format = "[$user]($style)@"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "dimmed fg:cyan"

# Prompt symbols
[character]
success_symbol = "[â¯](bold fg:green)"
error_symbol = "[â¯](bold fg:red)"
vimcmd_symbol = "[â®](bold fg:yellow)"

[directory]
truncation_length = 4
truncation_symbol = "â€¦/"
style = "bold fg:blue"

[cmd_duration]
min_time = 500
format = "â± [$duration]($style) "
style = "bold fg:orange"

[git_branch]
symbol = "ï˜ "
format = "[$symbol$branch]($style) "
style = "bold fg:purple"

[git_status]
style = "bold fg:purple"
conflicted = "âš”ï¸ "
ahead = "â‡¡${count}"
behind = "â‡£${count}"
stashed = "ğŸ“¦ "
diverged = "â‡•"
modified = "ï© "
untracked = "ï "

[time]
disabled = false
format = "ğŸ•™ [$time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "fg:comment"
